login:
  input_id:
    xpath: //*[@id="id"]
  input_password:
    xpath: //*[@id="pass"]
  click_submit:
    xpath: //*[@id='input_form']/form/p/input

home:
  click_point_confirm:
    action: click
    xpath: //*[@id="LnkV0800_002Top"]
